sudo: required
dist: trusty
addons:
  chrome: stable
language: java
jdk: openjdk8
services: mysql
install: true
  - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/
- export CHROME_BIN=chromium-browser
- mysql -e 'DROP DATABASE IF EXISTS alumnos;'
- mysql -e 'CREATE DATABASE IF NOT EXISTS alumnos;'
- mysql -e 'select database();'
- mysql -e 'SHOW DATABASES;'
- mysql -e 'USE alumnos;'  
- mysql -e 'select database();'
- mysql -e 'CREATE TABLE alumno (idAlumno int(11) NOT NULL, nombre varchar(45) DEFAULT NULL, edad int(11) DEFAULT NULL, calificacion int(11) DEFAULT NULL, email varchar(45) DEFAULT NULL, PRIMARY KEY (idAlumno)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;'
script:
- mvn install
- whereis google-chrome-stable
- whereis chromedriver
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y