sudo: required
dist: xenial
addons:
  chrome: stable
language: java
jdk: openjdk8
services: mysql
before deploy:
    -pip install travis-wait-improved
install: true
    - wget -N https://chromedriver.storage.googleapis.com/87.0.4280.66-1/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
before_script:
    - wget https://chromedriver.storage.googleapis.com/87.0.4280.66-1/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo apt-get install libnss3
    - sudo apt-get --only-upgrade install google-chrome-stable
    - sudo cp chromedriver /usr/local/bin/.
    - sudo chmod +x /usr/local/bin/chromedriver
    - export DISPLAY=:99.0
    - sleep 3
script:
    - mvn install
    - whereis google-chrome-stable
    - whereis chromedriver
    - mvn -Dtest=TestFacebook -e
before_install:
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y
  - sudo mysql -e 'CREATE DATABASE alumnos; USE alumnos; CREATE TABLE alumnos.Alumno (idAlumno int(11) NOT NULL, nombre varchar(45) DEFAULT NULL, edad int(11) DEFAULT NULL, calificacion int(11) DEFAULT NULL, email varchar(45) DEFAULT NULL, PRIMARY KEY (idAlumno));'
  - sudo chmod +x /home/travis/build/leonelsosav/my-app/src/test/resources/chromedriver